"""Genuine heavy-tailed (Lévy) UNITARY shift for a discrete-time quantum walk.

``qrw_heavy_tail.HeavyTailAdaptiveQRW`` is explicitly a *classical* surrogate: it
samples Bernoulli/Pareto jumps outside the quantum inference path, which is why
every tail claim built on it was retracted (final_report §7). This module
supplies the missing piece — a shift operator that is heavy-tailed **and**
exactly unitary.

Construction
------------
On a cycle of ``N`` positions the conditional shift is diagonal in momentum. The
standard nearest-neighbour shift multiplies momentum mode ``k`` by ``exp(-ik)``
for the coin-up component and ``exp(+ik)`` for coin-down. Generalising the phase
to

    φ_α(k) = sign(k) · |k|^α ,      k ∈ [-π, π)

keeps every eigenvalue on the unit circle, so the operator stays **exactly
unitary for every α** — unitarity is structural here, not approximate. Two
properties make it the right object:

* ``α = 1`` reproduces the ordinary ±1 translation *exactly* (φ₁(k) = k), so the
  construction is a strict generalisation of the existing walk.
* For ``α < 1`` the phase has a ``|k|^α`` cusp at ``k = 0``. A non-analytic
  symbol has Fourier coefficients with power-law decay, giving hopping
  amplitudes ``~ |x|^{-(1+α)}`` — i.e. genuine Lévy flights generated by a
  unitary, rather than by classical jump sampling.

Boundary conditions
-------------------
The momentum construction requires a *periodic* lattice, unlike
``QuantumRandomWalk`` which uses a non-wrapping line. Long-range hopping reaches
the lattice edge quickly, so :meth:`LevyUnitaryQRW.wraparound_mass` is provided
and callers must check it: a result whose probability has wrapped around the
cycle is an artifact, not a heavy tail.
"""

from __future__ import annotations

import numpy as np

from .coin_operators import hadamard_coin
from .qrw_core import CoinInput, _coin_from_input, _initial_coin

__all__ = [
    "levy_momentum_phase",
    "levy_shift_operator",
    "LevyUnitaryQRW",
]


def _validate_positions(n_positions: int) -> None:
    if isinstance(n_positions, bool) or not isinstance(n_positions, int):
        raise TypeError("n_positions must be an integer")
    if n_positions < 3 or n_positions % 2 == 0:
        raise ValueError("n_positions must be an odd integer of at least 3")


def _validate_alpha(alpha: float) -> float:
    value = float(alpha)
    if not np.isfinite(value):
        raise ValueError("alpha must be finite")
    if not 0.0 < value <= 2.0:
        raise ValueError("alpha must lie in (0, 2]")
    return value


def levy_momentum_phase(n_positions: int, alpha: float) -> np.ndarray:
    """Return ``φ_α(k) = sign(k)|k|^α`` on the FFT momentum grid.

    The grid follows ``numpy.fft`` ordering so the returned array can multiply an
    FFT result directly. ``alpha=1`` yields exactly ``k``.
    """
    _validate_positions(n_positions)
    value = _validate_alpha(alpha)
    k = 2.0 * np.pi * np.fft.fftfreq(n_positions)
    return np.sign(k) * np.abs(k) ** value


def levy_shift_operator(
    n_positions: int,
    alpha: float,
    *,
    direction: int = 1,
) -> np.ndarray:
    """Build the explicit ``(N, N)`` circulant Lévy shift.

    ``direction=+1`` moves probability toward increasing position (the coin-up
    branch); ``direction=-1`` is its inverse. Every eigenvalue has unit modulus,
    so the returned matrix is unitary to machine precision. This dense form
    exists for verification; :class:`LevyUnitaryQRW` applies the same operator in
    ``O(N log N)`` via FFT.
    """
    if direction not in (1, -1):
        raise ValueError("direction must be +1 or -1")
    phi = levy_momentum_phase(n_positions, alpha)
    eigenvalues = np.exp(-1j * float(direction) * phi)
    # A circulant C[x, y] = c[(x - y) mod N] has eigenvalues fft(c); invert that.
    first_column = np.fft.ifft(eigenvalues)
    index = np.arange(n_positions)
    offsets = (index[:, None] - index[None, :]) % n_positions
    return first_column[offsets]


class LevyUnitaryQRW:
    """Coined quantum walk whose shift is a heavy-tailed unitary on a cycle.

    Set ``alpha=1`` to recover the ordinary nearest-neighbour walk (on a
    periodic lattice); ``alpha<1`` produces genuine Lévy flights driven by the
    unitary itself rather than by classical jump sampling.
    """

    def __init__(
        self,
        n_positions: int,
        alpha: float,
        coin: CoinInput = "hadamard",
        initial_coin_state: np.ndarray | None = None,
    ) -> None:
        _validate_positions(n_positions)
        self.n_positions = n_positions
        self.alpha = _validate_alpha(alpha)
        self.positions = np.arange(n_positions, dtype=np.int64) - n_positions // 2
        self.initial_index = n_positions // 2
        self.coin = _coin_from_input(coin)
        self.initial_coin_state = _initial_coin(initial_coin_state)
        self._phase_up = np.exp(-1j * levy_momentum_phase(n_positions, self.alpha))
        self._phase_down = np.conjugate(self._phase_up)
        self.psi = np.zeros((2, n_positions), dtype=np.complex128)
        self.reset()

    def reset(self) -> None:
        """Restore the localized initial state at the lattice centre."""
        self.psi.fill(0.0)
        self.psi[:, self.initial_index] = self.initial_coin_state
        self.time = 0

    def set_coin(self, coin: CoinInput) -> None:
        """Replace the coin operator (validated unitary)."""
        self.coin = _coin_from_input(coin)

    def _shift(self, coin_state: np.ndarray) -> np.ndarray:
        """Apply the conditional Lévy shift in momentum space."""
        spectrum = np.fft.fft(coin_state, axis=1)
        spectrum[0] *= self._phase_up
        spectrum[1] *= self._phase_down
        return np.fft.ifft(spectrum, axis=1)

    def step(self, coin_matrix: np.ndarray | None = None) -> np.ndarray:
        """Apply one coin-then-Lévy-shift evolution step."""
        coin = self.coin if coin_matrix is None else _coin_from_input(coin_matrix)
        self.psi = self._shift(coin @ self.psi)
        self.time += 1
        return self.get_probability()

    def run(self, n_steps: int) -> np.ndarray:
        """Advance by ``n_steps`` and return the final position marginal."""
        if isinstance(n_steps, bool) or not isinstance(n_steps, int):
            raise TypeError("n_steps must be an integer")
        if n_steps < 0:
            raise ValueError("n_steps must be non-negative")
        for _ in range(n_steps):
            self.step()
        return self.get_probability()

    def get_probability(self) -> np.ndarray:
        """Return the current position marginal."""
        return np.sum(np.abs(self.psi) ** 2, axis=0).real

    def norm(self) -> float:
        """Return the total probability (unitary evolution keeps this at 1)."""
        return float(np.sum(np.abs(self.psi) ** 2))

    def variance(self) -> float:
        """Return the variance of the current position distribution."""
        probability = self.get_probability()
        mean = float(probability @ self.positions)
        return float(probability @ (self.positions - mean) ** 2)

    def wraparound_mass(self, edge_fraction: float = 0.1) -> float:
        """Probability sitting in the outer ``edge_fraction`` of the cycle.

        Long-range hopping can wrap around the periodic lattice, which would
        masquerade as a heavy tail. Callers should treat a non-negligible value
        as an invalid run and enlarge ``n_positions``.
        """
        if not 0.0 < edge_fraction < 0.5:
            raise ValueError("edge_fraction must lie in (0, 0.5)")
        probability = self.get_probability()
        width = max(1, int(self.n_positions * edge_fraction))
        return float(probability[:width].sum() + probability[-width:].sum())

    def tail_mass(self, threshold: int) -> float:
        """Probability beyond ``|position| >= threshold`` (a tail diagnostic)."""
        if isinstance(threshold, bool) or not isinstance(threshold, int):
            raise TypeError("threshold must be an integer")
        if threshold < 0:
            raise ValueError("threshold must be non-negative")
        probability = self.get_probability()
        return float(probability[np.abs(self.positions) >= threshold].sum())
